/*
 ESTE SCRIPT CREA UNA TRANSACCIÓN CON DOS SAVEPOINT PARA
 INSERTAR DATOS EN LA TABLA 'pacientes' Y EN LA TABLA 'pacientes_telefonos':
 */
-- ES NECESARIO SETEAR EL AUTOCOMMIT EN 0 PARA PODER REALIZAR INSERCIONES/ELIMINACIONES
SELECT @@AUTOCOMMIT;
SET AUTOCOMMIT = 0;
-- INICIA LA TRANSACCIÓN
START TRANSACTION;
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (44769256, 'O'' Liddy', 'Gareth', '2009-09-01', '4454 Steensland Plaza', 'goliddy0@loc.gov', 'OSPEDYC (Obra Social de Entidades Deportivas y Civiles)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (54900113, 'Filipczak', 'Morissa', '1980-03-19', '78 Fieldstone Lane', 'mfilipczak1@comsenz.com', 'AMFFA (Asociación Mutual de los Ferroviarios Argentinos)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (22262837, 'Strephan', 'Norbert', '2001-09-06', '4638 Northridge Court', 'nstrephan2@google.co.uk', 'Galeno');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (36108368, 'Robson', 'Jessamyn', '2013-02-20', '0697 Southridge Park', 'jrobson3@theguardian.com', 'Obras Sociales Provinciales (varias según cada provincia)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (46932199, 'Frankham', 'Edyth', '1989-04-09', '2 Lotheville Road', 'efrankham4@skype.com', 'OSPJN (Obra Social del Poder Judicial de la Nación)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (13815315, 'Nesby', 'Averell', '1985-05-27', '4047 Dwight Alley', 'anesby5@google.es', 'Swiss Medical');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (34329957, 'McClelland', 'Jandy', '1994-08-23', '258 Spohn Pass', 'jmcclelland6@globo.com', 'UOM (Unión Obrera Metalúrgica)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (43629998, 'Spadotto', 'Eustace', '1996-01-14', '113 Independence Terrace', 'espadotto7@pbs.org', 'Obras Sociales Provinciales (varias según cada provincia)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (17604869, 'Trever', 'Randal', '1966-12-22', '626 Mifflin Place', 'rtrever8@marriott.com', 'IAPOS (Instituto Autárquico Provincial de Obra Social)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (16315838, 'Giovanardi', 'Abba', '2001-04-30', '2914 Boyd Drive', 'agiovanardi9@ted.com', 'OSECAC (Obra Social de Empleados de Comercio y Actividades Civiles)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (39527472, 'Caillou', 'Barbaraanne', '1978-12-27', '5 Mayfield Place', 'bcailloua@merriam-webster.com', 'AMP (Asociación Mutual del Personal de la Universidad Nacional de Tucumán)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (56731084, 'Wilding', 'Lorinda', '2002-11-11', '22210 Porter Parkway', 'lwildingb@delicious.com', 'OSPAT (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (38077059, 'Ivanovic', 'Averell', '1980-10-30', '80486 Cottonwood Place', 'aivanovicc@uol.com.br', 'OSPA (Obra Social del Personal de la Actividad Aseguradora)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (38045312, 'Conrad', 'Babara', '1978-02-24', '9436 Anderson Pass', 'bconradd@meetup.com', 'OSPAT (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (23468259, 'Caudrelier', 'Auberon', '1973-06-25', '43879 Vidon Point', 'acaudreliere@etsy.com', 'OSPAT (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (55991885, 'Westphal', 'Augustin', '1994-07-03', '40 Lunder Street', 'awestphalf@tripod.com', 'OSECAC (Obra Social de Empleados de Comercio y Actividades Civiles)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (28362954, 'Jacobovitz', 'Marcelle', '2012-12-07', '418 Melody Way', 'mjacobovitzg@acquirethisname.com', 'Obras Sociales Provinciales (varias según cada provincia)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (17766885, 'Castlake', 'Early', '2009-05-26', '6083 Menomonie Avenue', 'ecastlakeh@surveymonkey.com', 'OSMATA (Obra Social del Personal de la Industria Azucarera)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (40658197, 'McNeill', 'Dorise', '2006-04-01', '87 Lerdahl Lane', 'dmcneilli@webmd.com', 'OSPRERA (Obra Social de los Empleados de la República Argentina)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (42097553, 'Nagle', 'Kiersten', '1989-10-02', '6538 Reindahl Crossing', 'knaglej@kickstarter.com', 'OSFFENTOS (Obra Social Ferroviaria de Fomento)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (12053185, 'Kelloway', 'Betta', '2005-07-18', '6764 Eggendart Park', 'bkellowayk@nsw.gov.au', 'SADAIC (Sociedad Argentina de Autores y Compositores de Música)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (44601418, 'Rait', 'Bartlett', '1984-08-16', '82576 Manley Place', 'braitl@paypal.com', 'OSPATCA (Obra Social del Personal Auxiliar de Casas Particulares)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (26186630, 'Scard', 'Lutero', '1985-01-07', '4063 Canary Court', 'lscardm@pinterest.com', 'PARTICULAR');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (16353985, 'Jones', 'Gerik', '2009-09-02', '0476 Ohio Pass', 'gjonesn@globo.com', 'OSPRERA (Obra Social de los Empleados de la República Argentina)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (49174717, 'Vigar', 'Jenda', '1972-12-30', '278 Schurz Place', 'jvigaro@gnu.org', 'OSDE');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (38702849, 'Hrus', 'Merrili', '1966-08-01', '1 Esker Circle', 'mhrusp@weebly.com', 'OSPATCA (Obra Social del Personal Auxiliar de Casas Particulares)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (55129657, 'Crawley', 'Oswald', '1975-10-03', '59977 Hooker Court', 'ocrawleyq@slashdot.org', 'Sancor Salud');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (25472099, 'Ivetts', 'Zondra', '2007-04-25', '7 Mcbride Road', 'zivettsr@w3.org', 'IAPS (Instituto de Asistencia Social del Neuquén)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (23705804, 'Dohmer', 'Barney', '2009-11-27', '1443 Oakridge Lane', 'bdohmers@google.cn', 'OSPA (Obra Social del Personal de la Actividad Aseguradora)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (29613896, 'Kalker', 'Ranna', '1979-11-06', '53813 Shopko Road', 'rkalkert@cdc.gov', 'Swiss Medical');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (37855479, 'Sedger', 'Andrej', '1969-08-24', '460 Del Sol Hill', 'asedgeru@aboutads.info', 'Obra Social Bancaria Argentina');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (47566519, 'Dargavel', 'Waylan', '1998-05-15', '231 Crowley Court', 'wdargavelv@indiatimes.com', 'IAPS (Instituto de Asistencia Social del Neuquén)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (24564019, 'Seifert', 'Huey', '1968-10-31', '040 Carberry Junction', 'hseifertw@goo.ne.jp', 'OSEF (Obra Social del Estado Fueguino)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (37846605, 'Hards', 'Jared', '1964-06-02', '4486 Westridge Way', 'jhardsx@google.es', 'OSMATA (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (26861763, 'Haggett', 'Anabella', '2007-02-06', '4678 Lawn Hill', 'ahaggetty@salon.com', 'PARTICULAR');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (23960440, 'Crippill', 'Bertrand', '1983-02-26', '639 Rigney Park', 'bcrippillz@twitpic.com', 'OSPA (Obra Social del Personal de la Actividad Aseguradora)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (20279900, 'Thomson', 'Tyrone', '1977-09-02', '4285 Spohn Avenue', 'tthomson10@nba.com', 'DASPU (Dirección de Asistencia Social del Personal Universitario)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (25401313, 'Fossey', 'Nerta', '1977-12-14', '651 Redwing Trail', 'nfossey11@prnewswire.com', 'AMEPA (Asociación Mutual de Empleados del Poder Judicial)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (14599923, 'Bengtsson', 'Griselda', '1981-10-09', '68856 Thierer Point', 'gbengtsson12@howstuffworks.com', 'OSPJN (Obra Social del Poder Judicial de la Nación)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (52338872, 'Reis', 'Selene', '2011-07-24', '39369 Riverside Trail', 'sreis13@dailymotion.com', 'Caja de Servicios Sociales de la Universidad Nacional del Sur');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (48296919, 'Rickman', 'Herculie', '2000-03-16', '20 Clove Junction', 'hrickman14@oaic.gov.au', 'PAMI (Programa de Atención Médica Integral)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (18019866, 'Broker', 'Olivette', '2001-10-05', '384 Graceland Point', 'obroker15@cyberchimps.com', 'OSFFENTOS (Obra Social Ferroviaria de Fomento)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (44686064, 'Woodington', 'Normand', '1983-05-27', '744 Scofield Plaza', 'nwoodington16@home.pl', 'Caja de Servicios Sociales de la Universidad Nacional del Sur');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (28540169, 'Vertey', 'Carlos', '1969-10-04', '11 Towne Avenue', 'cvertey17@google.es', 'Obras Sociales Provinciales (varias según cada provincia)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (20058468, 'Vedenyakin', 'Karim', '1992-06-10', '4 Anhalt Terrace', 'kvedenyakin18@dailymotion.com', 'Caja de Servicios Sociales de la Universidad Nacional del Sur');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (44039429, 'Duffree', 'Aggie', '1981-05-27', '72 Sauthoff Place', 'aduffree19@intel.com', 'OSMATA (Obra Social del Personal de la Industria Azucarera)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (18067225, 'Konert', 'Brandtr', '2009-04-28', '9 Porter Point', 'bkonert1a@pbs.org', 'OSPEDYC (Obra Social de Entidades Deportivas y Civiles)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (32945781, 'Burnyeat', 'Vania', '1974-06-12', '178 Transport Alley', 'vburnyeat1b@live.com', 'IOMA (Instituto de Obra Médico Asistencial)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (49801418, 'Trumble', 'Lela', '1960-03-05', '8448 Lakewood Gardens Avenue', 'ltrumble1c@sciencedirect.com', 'AMEPA (Asociación Mutual de Empleados del Poder Judicial)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (37982781, 'Dougan', 'Jarred', '2003-01-14', '3417 Springs Hill', 'jdougan1d@cisco.com', 'IAPS (Instituto de Asistencia Social del Neuquén)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (45557392, 'Whitear', 'Erick', '2015-03-31', '55 Village Green Alley', 'ewhitear1e@aol.com', 'OSFFENTOS (Obra Social Ferroviaria de Fomento)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (14883599, 'Pilsworth', 'Rockie', '1982-07-12', '63377 Starling Alley', 'rpilsworth1f@amazonaws.com', 'Obra Social Bancaria Argentina');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (13974325, 'Priter', 'Had', '1962-10-23', '0187 Gina Drive', 'hpriter1g@w3.org', 'PAMI (Programa de Atención Médica Integral)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (54298760, 'Deaconson', 'Constance', '1961-07-26', '3 Esch Way', 'cdeaconson1h@census.gov', 'OSPEDYC (Obra Social de Entidades Deportivas y Civiles)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (42412540, 'Castanaga', 'Ax', '1998-10-07', '3 Graceland Pass', 'acastanaga1i@shareasale.com', 'OSPA (Obra Social del Personal de la Actividad Aseguradora)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (24008103, 'Dancey', 'Aluin', '1980-10-20', '60982 Cardinal Terrace', 'adancey1j@theglobeandmail.com', 'UOCRA (Unión Obrera de la Construcción de la República Argentina)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (45355913, 'Kobpac', 'Jay', '2002-04-12', '16 Stoughton Lane', 'jkobpac1k@si.edu', 'OSMATA (Obra Social del Personal de la Industria Azucarera)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (53995776, 'Giovanni', 'Niccolo', '1973-02-12', '5 Mccormick Terrace', 'ngiovanni1l@google.ca', 'IAPOS (Instituto Autárquico Provincial de Obra Social)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (18853246, 'Greaterex', 'Edyth', '1975-03-14', '77681 Upham Way', 'egreaterex1m@adobe.com', 'Sancor Salud');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (26460831, 'Rusted', 'Faulkner', '2011-03-25', '12 Ramsey Parkway', 'frusted1n@geocities.jp', 'Medicus');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (14815123, 'Jan', 'Kirstyn', '1982-11-20', '1558 Lunder Court', 'kjan1o@wikispaces.com', 'OSPATCA (Obra Social del Personal Auxiliar de Casas Particulares)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (38071144, 'Filippello', 'John', '1990-05-06', '406 Amoth Point', 'jfilippello1p@disqus.com', 'Caja de Servicios Sociales de la Universidad Nacional del Sur');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (39272104, 'Cranmere', 'Gabriel', '1991-12-11', '7 1st Terrace', 'gcranmere1q@usa.gov', 'Sancor Salud');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (40139447, 'Gronou', 'Chauncey', '1998-10-19', '53 Crownhardt Point', 'cgronou1r@github.io', 'OSMATA (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (56403036, 'Tolussi', 'Worden', '1976-03-19', '84 Thackeray Center', 'wtolussi1s@about.com', 'PARTICULAR');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (20000424, 'Taill', 'Olga', '1972-04-06', '487 Sherman Junction', 'otaill1t@booking.com', 'Medicus');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (34190665, 'Penketh', 'Adelice', '1970-10-13', '3814 Schiller Plaza', 'apenketh1u@answers.com', 'OSPV (Obra Social de Petroleros y Gas Privado de la Patagonia Austral)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (41942886, 'Prys', 'Saxe', '1980-02-04', '81 Towne Lane', 'sprys1v@ifeng.com', 'OSPAT (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (25739404, 'Corran', 'Amandi', '1968-08-09', '31 Acker Court', 'acorran1w@youtu.be', 'Obras Sociales Provinciales (varias según cada provincia)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (29842859, 'Gilgryst', 'Nisse', '1986-06-19', '6 Bluejay Hill', 'ngilgryst1x@weather.com', 'IAPOS (Instituto Autárquico Provincial de Obra Social)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (32984941, 'Bortoloni', 'Karalee', '1970-08-07', '3891 Loomis Hill', 'kbortoloni1y@go.com', 'OSPATCA (Obra Social del Personal Auxiliar de Casas Particulares)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (22254182, 'Chomicki', 'Shirlee', '1987-09-02', '431 Dawn Parkway', 'schomicki1z@plala.or.jp', 'OSPAT (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (15653994, 'Rennels', 'Ross', '1999-11-17', '763 Esch Junction', 'rrennels20@live.com', 'Obra Social Bancaria Argentina');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (50604715, 'Swyn', 'Michel', '1979-09-18', '43 Sloan Alley', 'mswyn21@hibu.com', 'AMP (Asociación Mutual del Personal de la Universidad Nacional de Tucumán)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (26487835, 'Figin', 'Clay', '1969-03-24', '5357 Spenser Road', 'cfigin22@slate.com', 'UOM (Unión Obrera Metalúrgica)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (51663994, 'Kenrick', 'Wendye', '1966-07-05', '8502 Bayside Crossing', 'wkenrick23@aboutads.info', 'Sancor Salud');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (23389370, 'Storrock', 'Deerdre', '2012-06-27', '3832 Sutteridge Place', 'dstorrock24@exblog.jp', 'Medicus');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (17931042, 'Witchard', 'Kore', '1963-09-19', '2 Bunker Hill Place', 'kwitchard25@howstuffworks.com', 'OSPATCA (Obra Social del Personal Auxiliar de Casas Particulares)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (55989961, 'Pavy', 'Dana', '1966-03-20', '51489 Lake View Street', 'dpavy26@imageshack.us', 'Medicus');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (43968764, 'Robbey', 'Asher', '1983-03-11', '246 Stone Corner Junction', 'arobbey27@cornell.edu', 'IAPS (Instituto de Asistencia Social del Neuquén)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (36796119, 'Kiff', 'Dorian', '1995-12-03', '77 Golf View Place', 'dkiff28@storify.com', 'AMEPA (Asociación Mutual de Empleados del Poder Judicial)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (46647824, 'Housbey', 'Hendrick', '1997-11-06', '6 Redwing Avenue', 'hhousbey29@github.io', 'Obra Social de la Universidad Nacional de Córdoba');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (42689413, 'Errigo', 'Vin', '2003-03-30', '8931 Straubel Terrace', 'verrigo2a@ning.com', 'Caja de Servicios Sociales de la Universidad Nacional del Sur');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (33704770, 'Tuffley', 'Nicola', '1996-01-23', '7 Hollow Ridge Junction', 'ntuffley2b@rediff.com', 'UPCN (Unión del Personal Civil de la Nación)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (37014801, 'Colman', 'Karleen', '1972-11-28', '506 Oneill Place', 'kcolman2c@reference.com', 'Accord Salud');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (19928102, 'Dalli', 'Anthony', '1987-02-01', '9030 Barby Pass', 'adalli2d@cbc.ca', 'Medicus');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (14010176, 'Rowcliffe', 'Antoni', '1965-11-01', '6048 Logan Lane', 'arowcliffe2e@nationalgeographic.com', 'OSPA (Obra Social del Personal de la Actividad Aseguradora)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (38325160, 'Gokes', 'Fae', '1966-06-01', '3 Shelley Point', 'fgokes2f@ning.com', 'OSMATA (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (31205338, 'Dedman', 'Zackariah', '2002-12-26', '34116 Sherman Pass', 'zdedman2g@sina.com.cn', 'OSPAT (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (41897996, 'Kares', 'Chick', '2000-12-06', '261 Eagle Crest Junction', 'ckares2h@artisteer.com', 'PARTICULAR');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (22819360, 'Spurrett', 'Lonnie', '1986-07-26', '3 Ryan Terrace', 'lspurrett2i@github.io', 'UOM (Unión Obrera Metalúrgica)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (37061752, 'Bigland', 'Valry', '1996-07-12', '629 Lerdahl Terrace', 'vbigland2j@biblegateway.com', 'OSPV (Obra Social de Petroleros y Gas Privado de la Patagonia Austral)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (23112911, 'Brastead', 'Lindsey', '1979-06-24', '980 Paget Drive', 'lbrastead2k@wisc.edu', 'UOM (Unión Obrera Metalúrgica)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (12478741, 'Gergus', 'Marwin', '1999-01-03', '98888 Truax Trail', 'mgergus2l@squidoo.com', 'AMEPA (Asociación Mutual de Empleados del Poder Judicial)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (26037202, 'Bartunek', 'Gav', '1993-10-07', '10 Sutherland Pass', 'gbartunek2m@yahoo.com', 'AMFFA (Asociación Mutual de los Ferroviarios Argentinos)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (14065661, 'Thom', 'Kiel', '1991-10-04', '0614 Bunting Place', 'kthom2n@people.com.cn', 'Obra Social de la Universidad Nacional de Córdoba');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (35958017, 'Pele', 'Madella', '1983-10-05', '66 Forest Pass', 'mpele2o@baidu.com', 'Sancor Salud');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (14077095, 'Lombard', 'Tansy', '1986-02-16', '029 Lighthouse Bay Drive', 'tlombard2p@netvibes.com', 'IOMA (Instituto de Obra Médico Asistencial)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (49477220, 'Eagland', 'Charo', '1973-01-13', '9 Westerfield Place', 'ceagland2q@ibm.com', 'IPAUSS (Instituto Provincial Autárquico Unificado de Seguridad Social)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (50765251, 'Asher', 'Frayda', '2009-06-26', '509 6th Trail', 'fasher2r@wisc.edu', 'PARTICULAR');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (33043507, 'Searchwell', 'Shayla', '2000-08-01', '9081 Norway Maple Drive', 'ssearchwell2s@gmpg.org', 'OSPAT (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (54809849, 'Ivery', 'Kameko', '2000-09-01', '81 7th Center', 'kivery2t@clickbank.net', 'OSFFENTOS (Obra Social Ferroviaria de Fomento)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (20673541, 'Bett', 'Sallyann', '1974-10-12', '35 Fieldstone Place', 'sbett2u@fda.gov', 'AMP (Asociación Mutual del Personal de la Universidad Nacional de Tucumán)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (27067766, 'Baughn', 'Timmi', '1996-12-02', '6375 Dixon Circle', 'tbaughn2v@imdb.com', 'Medicus');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (42494126, 'Kingsly', 'Peggi', '1990-04-28', '779 Cordelia Drive', 'pkingsly2w@aboutads.info', 'OSPATCA (Obra Social del Personal Auxiliar de Casas Particulares)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (14422108, 'Barge', 'Peadar', '1971-02-11', '3 Susan Park', 'pbarge2x@ow.ly', 'OSPA (Obra Social del Personal de la Actividad Aseguradora)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (41824177, 'Rising', 'Niccolo', '1969-01-28', '0 West Road', 'nrising2y@walmart.com', 'OSDE');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (55391019, 'Pickavant', 'Pat', '1969-12-09', '05 Eggendart Crossing', 'ppickavant2z@jimdo.com', 'PARTICULAR');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (43752812, 'Bambrick', 'Doe', '1970-11-14', '73 High Crossing Parkway', 'dbambrick30@flickr.com', 'OSPAT (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (28083943, 'Gorham', 'Cob', '1963-09-10', '51960 Magdeline Junction', 'cgorham31@livejournal.com', 'IAPS (Instituto de Asistencia Social del Neuquén)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (12467221, 'Willman', 'Eba', '1999-04-07', '63614 Anniversary Crossing', 'ewillman32@opera.com', 'OSPV (Obra Social de Petroleros y Gas Privado de la Patagonia Austral)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (22916672, 'Cassam', 'Caroline', '1968-05-30', '07 Basil Hill', 'ccassam33@godaddy.com', 'OSDE');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (44077068, 'Keddey', 'Pincas', '1972-11-15', '801 Monterey Point', 'pkeddey34@1688.com', 'UOM (Unión Obrera Metalúrgica)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (17237798, 'Rea', 'Ali', '2009-07-05', '89368 Shoshone Place', 'area35@tripadvisor.com', 'OSEF (Obra Social del Estado Fueguino)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (26465871, 'Holleworth', 'Tedda', '1990-01-02', '39115 Banding Hill', 'tholleworth36@house.gov', 'IOMA (Instituto de Obra Médico Asistencial)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (53240292, 'Kanzler', 'Theodosia', '2006-02-02', '83670 Porter Crossing', 'tkanzler37@mit.edu', 'OSMATA (Obra Social del Personal de la Industria Azucarera)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (14954467, 'Jepperson', 'Duffie', '2005-08-02', '61 Crownhardt Plaza', 'djepperson38@cargocollective.com', 'OSMATA (Obra Social del Personal de la Industria Azucarera)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (14678545, 'Schusterl', 'Stinky', '1963-07-21', '9025 Farragut Hill', 'sschusterl39@psu.edu', 'PAMI (Programa de Atención Médica Integral)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (34477243, 'Stevenson', 'Major', '1984-05-14', '73 Prairieview Parkway', 'mstevenson3a@multiply.com', 'UOM (Unión Obrera Metalúrgica)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (13278350, 'Valasek', 'Vinni', '1973-08-11', '67 Clyde Gallagher Junction', 'vvalasek3b@issuu.com', 'IAPOS (Instituto Autárquico Provincial de Obra Social)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (32434714, 'Tackley', 'Kingsley', '1962-01-08', '50 Helena Drive', 'ktackley3c@shutterfly.com', 'Swiss Medical');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (42577254, 'Danforth', 'Kacie', '2008-10-31', '069 Cottonwood Road', 'kdanforth3d@imageshack.us', 'OSMATA (Obra Social del Personal de la Industria Azucarera)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (19853691, 'Fawkes', 'Beckie', '1967-10-04', '37467 Pearson Trail', 'bfawkes3e@google.com', 'OSPV (Obra Social de Petroleros y Gas Privado de la Patagonia Austral)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (31192631, 'Sleite', 'Toinette', '1969-12-03', '3870 Anderson Center', 'tsleite3f@dot.gov', 'OSMATA (Obra Social del Personal de la Industria Azucarera)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (52086269, 'Godart', 'Orrin', '1997-02-22', '13 Arrowood Court', 'ogodart3g@pen.io', 'AMEPA (Asociación Mutual de Empleados del Poder Judicial)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (50231654, 'Rittmeyer', 'Sarette', '2015-08-18', '63 Susan Point', 'srittmeyer3h@wix.com', 'Obra Social de la Universidad Nacional de Córdoba');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (13498061, 'Petworth', 'Eadmund', '1987-03-25', '2228 Hudson Terrace', 'epetworth3i@businessinsider.com', 'Medicus');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (26734093, 'Seekings', 'Palmer', '1989-11-02', '763 Memorial Way', 'pseekings3j@github.com', 'IPAUSS (Instituto Provincial Autárquico Unificado de Seguridad Social)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (28492402, 'Frill', 'Brianna', '1970-12-31', '140 Truax Junction', 'bfrill3k@chron.com', 'Accord Salud');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (27139833, 'Titman', 'Corie', '2001-09-21', '0 8th Trail', 'ctitman3l@privacy.gov.au', 'OSECAC (Obra Social de Empleados de Comercio y Actividades Civiles)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (50035084, 'Malden', 'Amby', '1989-08-24', '04 Gale Alley', 'amalden3m@furl.net', 'OSEF (Obra Social del Estado Fueguino)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (14015974, 'Saffle', 'Jocko', '2004-11-17', '61914 Iowa Way', 'jsaffle3n@engadget.com', 'IAPS (Instituto de Asistencia Social del Neuquén)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (36292084, 'Shipway', 'Nicolle', '2009-05-29', '56 Dennis Street', 'nshipway3o@etsy.com', 'Obra Social Bancaria Argentina');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (37766551, 'Stratten', 'Sawyer', '1971-07-28', '6547 Blue Bill Park Crossing', 'sstratten3p@foxnews.com', 'Accord Salud');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (31881425, 'Bunnell', 'Mead', '1995-06-22', '269 Burrows Place', 'mbunnell3q@etsy.com', 'Obra Social de la Universidad Nacional de Córdoba');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (23230922, 'Flacknell', 'Werner', '2015-10-16', '7586 Nevada Drive', 'wflacknell3r@reverbnation.com', 'Obras Sociales Provinciales (varias según cada provincia)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (41322208, 'Licciardiello', 'Felecia', '1967-01-23', '4052 Swallow Hill', 'flicciardiello3s@bigcartel.com', 'OSFFENTOS (Obra Social Ferroviaria de Fomento)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (26752226, 'Block', 'Cyndy', '1982-11-30', '6 Bobwhite Street', 'cblock3t@java.com', 'OSPV (Obra Social de Petroleros y Gas Privado de la Patagonia Austral)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (50022992, 'Rotter', 'Marjory', '2013-05-14', '7394 Fallview Center', 'mrotter3u@fotki.com', 'IAPS (Instituto de Asistencia Social del Neuquén)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (46783996, 'Gothrup', 'Reagan', '2006-05-17', '29 Trailsway Circle', 'rgothrup3v@google.cn', 'OSMATA (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (24262784, 'Skates', 'Emiline', '2002-01-16', '3 Glendale Crossing', 'eskates3w@cnn.com', 'OSEF (Obra Social del Estado Fueguino)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (54851166, 'Sindle', 'Venita', '2007-05-12', '8 Michigan Terrace', 'vsindle3x@edublogs.org', 'OSPA (Obra Social del Personal de la Actividad Aseguradora)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (36829967, 'Strute', 'Donella', '2014-09-17', '015 Anzinger Point', 'dstrute3y@bbb.org', 'AMFFA (Asociación Mutual de los Ferroviarios Argentinos)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (46675055, 'Slack', 'Bill', '1970-02-04', '9071 North Terrace', 'bslack3z@ehow.com', 'OSEF (Obra Social del Estado Fueguino)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (42313718, 'Shiel', 'Arman', '1980-03-15', '68845 Mosinee Circle', 'ashiel40@xrea.com', 'Obras Sociales Provinciales (varias según cada provincia)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (26131545, 'Taw', 'Chaunce', '1960-07-17', '52583 Ilene Circle', 'ctaw41@homestead.com', 'Medicus');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (45271575, 'Tessier', 'Jimmy', '1997-05-08', '16163 Darwin Drive', 'jtessier42@woothemes.com', 'UOM (Unión Obrera Metalúrgica)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (36170272, 'Bridson', 'Yolane', '1961-08-09', '91673 Northport Junction', 'ybridson43@cdbaby.com', 'OSPJN (Obra Social del Poder Judicial de la Nación)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (55876664, 'Goulthorp', 'Alexine', '1976-03-27', '700 Jackson Point', 'agoulthorp44@cmu.edu', 'DASPU (Dirección de Asistencia Social del Personal Universitario)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (45197754, 'Amerighi', 'Hana', '2006-07-22', '582 Montana Trail', 'hamerighi45@uiuc.edu', 'Accord Salud');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (50978342, 'Stodd', 'Kennie', '1971-08-15', '7 Monterey Court', 'kstodd46@ning.com', 'OSMATA (Obra Social del Personal de la Industria Azucarera)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (29645507, 'Cubitt', 'Rosemary', '2006-02-24', '98 Mallard Terrace', 'rcubitt47@amazon.co.uk', 'OSPAT (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (41297582, 'Checci', 'Daniella', '1979-02-01', '82099 Sage Junction', 'dchecci48@discuz.net', 'IAPS (Instituto de Asistencia Social del Neuquén)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (33137714, 'Kinnoch', 'Brandise', '1963-04-10', '317 Scofield Point', 'bkinnoch49@icq.com', 'OSPRERA (Obra Social de los Empleados de la República Argentina)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (33727670, 'Cristoforetti', 'Sheila-kathryn', '2007-06-10', '81 Bobwhite Way', 'scristoforetti4a@nsw.gov.au', 'Galeno');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (49605213, 'Haine', 'Berni', '1971-08-21', '56977 Daystar Drive', 'bhaine4b@ft.com', 'IPAUSS (Instituto Provincial Autárquico Unificado de Seguridad Social)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (55916076, 'Oakland', 'Ginni', '1996-08-31', '68230 Autumn Leaf Court', 'goakland4c@nasa.gov', 'UOM (Unión Obrera Metalúrgica)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (47526774, 'Lukock', 'Rhianon', '1990-07-03', '48 Marcy Place', 'rlukock4d@indiegogo.com', 'OSMATA (Obra Social del Personal de la Actividad del Turf)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (52673450, 'Meak', 'Alejoa', '1982-12-12', '698 Moulton Lane', 'ameak4e@sitemeter.com', 'AMEPA (Asociación Mutual de Empleados del Poder Judicial)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (41982467, 'Dagger', 'Xylina', '2010-04-11', '76494 Monument Avenue', 'xdagger4f@wisc.edu', 'OSPRERA (Obra Social de los Empleados de la República Argentina)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (48070936, 'Maydway', 'Roberto', '2000-10-31', '0 Victoria Lane', 'rmaydway4g@washington.edu', 'Accord Salud');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (23783913, 'Lill', 'Alphonse', '1991-06-18', '838 Sherman Street', 'alill4h@bluehost.com', 'OSEF (Obra Social del Estado Fueguino)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (14501958, 'Galbraeth', 'Flss', '1999-03-01', '83847 Eastwood Parkway', 'fgalbraeth4i@salon.com', 'IOMA (Instituto de Obra Médico Asistencial)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (19392790, 'Willingam', 'Edlin', '1976-06-12', '89 Shoshone Crossing', 'ewillingam4j@army.mil', 'OSFFENTOS (Obra Social Ferroviaria de Fomento)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (26831952, 'Madden', 'Elliot', '2004-11-29', '838 Killdeer Terrace', 'emadden4k@google.ru', 'OSPA (Obra Social del Personal de la Actividad Aseguradora)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (44473882, 'McCreath', 'Vinson', '2009-11-08', '0 John Wall Crossing', 'vmccreath4l@blog.com', 'OSPA (Obra Social del Personal de la Actividad Aseguradora)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (50776376, 'Cosyns', 'Tony', '1967-03-17', '5872 Di Loreto Center', 'tcosyns4m@tuttocitta.it', 'OSEF (Obra Social del Estado Fueguino)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (18170313, 'McClenan', 'Sandye', '1974-05-22', '8621 Sommers Parkway', 'smcclenan4n@indiatimes.com', 'UPCN (Unión del Personal Civil de la Nación)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (33729020, 'Sedgeworth', 'Freeman', '1973-10-29', '261 Transport Point', 'fsedgeworth4o@chronoengine.com', 'SADAIC (Sociedad Argentina de Autores y Compositores de Música)');
          insert into pacientes (dni, apellido, nombre, fecha_nacimiento, domicilio, correo_electronico, obra_social) values (41355788, 'Walkley', 'Park', '1993-07-08', '848 Roth Street', 'pwalkley4p@fda.gov', 'AMP (Asociación Mutual del Personal de la Universidad Nacional de Tucumán)');
-- SE CREA UN PRIMER SAVEPOINT
SAVEPOINT save_pacientes;
-- SE SIGUE INSERTANDO DATOS, AHORA EN LA TABLA 'pacientes_telefonos'
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (1, 'FIJO', '9593934882');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (2, 'CELULAR', '3581931312');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (3, 'CELULAR', '1433654774');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (4, 'CELULAR', '3353772627');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (5, 'FIJO', '2818184252');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (6, 'FIJO', '8959755380');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (7, 'CELULAR', '5258246631');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (8, 'CELULAR', '6408398377');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (9, 'FIJO', '2123486052');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (10, 'CELULAR', '6934516821');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (11, 'CELULAR', '6799420849');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (12, 'FIJO', '6938558138');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (13, 'CELULAR', '5688917849');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (14, 'CELULAR', '7662891221');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (15, 'FIJO', '8153486161');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (16, 'FIJO', '4681034675');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (17, 'FIJO', '8019819377');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (18, 'CELULAR', '5301031224');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (19, 'FIJO', '9721514893');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (20, 'FIJO', '9699754684');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (21, 'FIJO', '7616818659');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (22, 'FIJO', '3007144412');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (23, 'FIJO', '5998756000');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (24, 'CELULAR', '7437948788');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (25, 'FIJO', '5089014942');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (26, 'FIJO', '4041094371');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (27, 'FIJO', '9522878161');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (28, 'FIJO', '2582453609');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (29, 'FIJO', '3006818170');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (30, 'CELULAR', '8216999036');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (31, 'CELULAR', '4763056397');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (32, 'CELULAR', '3633301262');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (33, 'CELULAR', '9193383179');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (34, 'FIJO', '1508495313');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (35, 'CELULAR', '5081921669');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (36, 'CELULAR', '3083119696');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (37, 'CELULAR', '4953198105');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (38, 'CELULAR', '8609679884');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (39, 'CELULAR', '9174335541');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (40, 'CELULAR', '5756889424');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (41, 'FIJO', '7167714015');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (42, 'FIJO', '1791655539');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (43, 'CELULAR', '2025111906');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (44, 'FIJO', '1059282333');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (45, 'FIJO', '9385503289');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (46, 'CELULAR', '6971622924');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (47, 'CELULAR', '5913641139');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (48, 'FIJO', '5441449845');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (49, 'CELULAR', '9063137709');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (50, 'FIJO', '5562517755');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (51, 'CELULAR', '6345174155');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (52, 'CELULAR', '3144898825');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (53, 'CELULAR', '4885192211');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (54, 'CELULAR', '8434888091');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (55, 'FIJO', '6165414705');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (56, 'CELULAR', '3155644064');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (57, 'CELULAR', '9169696581');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (58, 'FIJO', '2731623258');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (59, 'CELULAR', '9005971890');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (60, 'FIJO', '8641483883');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (61, 'FIJO', '1119262296');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (62, 'FIJO', '2476358065');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (63, 'FIJO', '5873388944');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (64, 'CELULAR', '4269898524');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (65, 'CELULAR', '6542376026');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (66, 'FIJO', '5139223259');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (67, 'FIJO', '7934460547');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (68, 'FIJO', '1276989703');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (69, 'CELULAR', '1022520536');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (70, 'FIJO', '8643091431');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (71, 'FIJO', '9099475885');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (72, 'CELULAR', '5663601133');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (73, 'CELULAR', '2055610984');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (74, 'FIJO', '2825545299');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (75, 'CELULAR', '4895254728');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (76, 'CELULAR', '1498028851');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (77, 'FIJO', '6781061484');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (78, 'CELULAR', '6987556845');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (79, 'CELULAR', '3921075160');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (80, 'CELULAR', '6261947516');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (81, 'FIJO', '6123817940');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (82, 'CELULAR', '4054828469');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (83, 'FIJO', '7429066909');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (84, 'CELULAR', '5091085136');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (85, 'FIJO', '2535293970');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (86, 'CELULAR', '9494665154');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (87, 'CELULAR', '3738250362');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (88, 'FIJO', '5443879508');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (89, 'CELULAR', '8926045021');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (90, 'CELULAR', '5596059266');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (91, 'FIJO', '1356726364');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (92, 'CELULAR', '3058580068');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (93, 'FIJO', '5972091665');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (94, 'CELULAR', '3157650116');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (95, 'CELULAR', '9077018717');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (96, 'FIJO', '3126658354');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (97, 'FIJO', '5381881290');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (98, 'CELULAR', '3729313110');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (99, 'FIJO', '3903405899');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (100, 'FIJO', '3351365352');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (101, 'FIJO', '5884833941');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (102, 'FIJO', '1103842733');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (103, 'CELULAR', '8328616591');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (104, 'CELULAR', '2286536670');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (105, 'FIJO', '6827214654');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (106, 'FIJO', '1877397047');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (107, 'FIJO', '9077593684');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (108, 'CELULAR', '4839449812');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (109, 'CELULAR', '9026928320');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (110, 'FIJO', '2697062633');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (111, 'FIJO', '7721851038');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (112, 'FIJO', '3378390266');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (113, 'CELULAR', '6808928165');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (114, 'CELULAR', '2993776570');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (115, 'CELULAR', '9518542900');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (116, 'CELULAR', '2818123269');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (117, 'FIJO', '6896179310');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (118, 'CELULAR', '1943097168');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (119, 'CELULAR', '6976227337');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (120, 'FIJO', '6441509498');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (121, 'FIJO', '8374212418');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (122, 'CELULAR', '5125666011');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (123, 'CELULAR', '3248620374');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (124, 'CELULAR', '4951866937');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (125, 'CELULAR', '9132091951');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (126, 'FIJO', '9245929778');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (127, 'CELULAR', '1132561100');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (128, 'CELULAR', '5627799205');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (129, 'FIJO', '2125189897');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (130, 'CELULAR', '1179127417');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (131, 'CELULAR', '5853483899');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (132, 'FIJO', '8936919697');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (133, 'CELULAR', '1681185731');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (134, 'FIJO', '3716266698');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (135, 'CELULAR', '1697035054');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (136, 'FIJO', '7061828995');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (137, 'CELULAR', '2925329342');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (138, 'FIJO', '2784125571');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (139, 'CELULAR', '7468537757');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (140, 'CELULAR', '1507233972');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (141, 'FIJO', '3826183800');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (142, 'FIJO', '5018213324');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (143, 'FIJO', '4395580728');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (144, 'FIJO', '4046415932');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (145, 'FIJO', '1379977279');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (146, 'FIJO', '5122914710');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (147, 'CELULAR', '7164928521');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (148, 'FIJO', '7073619509');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (149, 'CELULAR', '3633773329');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (150, 'FIJO', '8117882179');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (151, 'CELULAR', '2444085204');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (152, 'FIJO', '9021511486');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (153, 'FIJO', '2631016138');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (154, 'FIJO', '1753767966');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (155, 'CELULAR', '4621744597');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (156, 'CELULAR', '7166344665');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (157, 'FIJO', '3495063727');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (158, 'FIJO', '4382484444');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (159, 'CELULAR', '9314924055');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (160, 'CELULAR', '1101890912');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (161, 'CELULAR', '7905393502');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (162, 'FIJO', '1375704371');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (163, 'CELULAR', '6444508200');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (164, 'FIJO', '6301147076');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (165, 'CELULAR', '8036201698');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (166, 'CELULAR', '2477738340');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (167, 'FIJO', '6047883537');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (168, 'CELULAR', '3331289600');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (169, 'CELULAR', '9432880481');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (170, 'CELULAR', '8316873763');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (11, 'FIJO', '7853728740');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (12, 'FIJO', '7939524906');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (13, 'CELULAR', '8422702244');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (54, 'FIJO', '8438369365');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (55, 'FIJO', '1836479002');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (56, 'CELULAR', '1491174952');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (17, 'CELULAR', '2059411817');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (18, 'FIJO', '4499768667');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (89, 'CELULAR', '1229357681');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (80, 'FIJO', '5937287811');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (81, 'CELULAR', '1269094420');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (12, 'FIJO', '6137203250');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (13, 'FIJO', '9974431993');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (94, 'CELULAR', '1294705735');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (95, 'CELULAR', '1445873258');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (96, 'CELULAR', '5882525696');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (17, 'FIJO', '2085303087');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (18, 'FIJO', '5305101819');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (19, 'FIJO', '5844427015');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (110, 'FIJO', '3735009915');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (111, 'CELULAR', '4152463534');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (112, 'CELULAR', '5676154907');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (13, 'CELULAR', '9899460795');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (14, 'CELULAR', '6212408144');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (151, 'CELULAR', '4567571007');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (161, 'CELULAR', '1159706971');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (170, 'CELULAR', '3955071703');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (18, 'CELULAR', '1185618624');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (19, 'CELULAR', '5368917181');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (20, 'FIJO', '5928213779');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (71, 'FIJO', '3363643182');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (72, 'FIJO', '6795777881');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (73, 'FIJO', '4587169771');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (24, 'FIJO', '4006211973');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (25, 'FIJO', '2635268741');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (86, 'CELULAR', '8349851236');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (87, 'FIJO', '4677766961');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (88, 'FIJO', '5215604760');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (29, 'FIJO', '2472122825');
          insert into pacientes_telefonos (id_paciente, descripcion, telefono) values (20, 'CELULAR', '2138600242');
-- SE CREA UN SEGUNDO SAVEPOINT
SAVEPOINT save_pacientes_telefonos;
-- SE REALIZA UN COMMIT PARA CONFIRMAR LOS CAMBIOS
  COMMIT;
-- PARA CHEQUEAR QUE LOS DATOS SE CARGARON CORRECTAMENTE, PUEDE DESCOMENTAR Y EJECUTAR LAS SIGUIENTES LINEAS
-- SELECT * FROM pacientes;
-- SELECT * FROM pacientes_telefonos;
  
