/*
 ESTE SCRIPT INSERTA DATOS EN LA TABLA 'medicos' Y EN LA TABLA 'medicos_telefonos':
 */

-- Inserción de datos en la tabla 'medicos'
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (608062, 'Braunston', 'Boot', '1961-03-03', 'bbraunston0@nationalgeographic.com', 'Clínica', 2260);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (36380334, 'Paur', 'Montague', '1969-12-11', 'mpaur1@wsj.com', 'Pediatría', 8156);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (3057710, 'Bootell', 'Franz', '1967-08-10', 'fbootell2@bbc.co.uk', 'Traumatología', 6539);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (2657062, 'Heasman', 'Kinny', '1963-06-24', 'kheasman3@imdb.com', 'Dermatología', 3662);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (19626438, 'Liepina', 'Baxy', '1981-02-21', 'bliepina4@storify.com', 'Clínica', 5198);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (21323069, 'Westerman', 'Emlyn', '1989-04-18', 'ewesterman5@angelfire.com', 'Cardiología', 7115);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (20462115, 'Allen', 'Arleen', '1988-12-30', 'aallen6@nyu.edu', 'Clínica', 3142);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (2945556, 'Hindrick', 'Euell', '1963-12-03', 'ehindrick7@dion.ne.jp', 'Psicología', 7293);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (36957604, 'Creasy', 'Lothario', '1965-11-01', 'lcreasy8@bigcartel.com', 'Psiquiatría', 4189);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (9858225, 'Yakovich', 'Llywellyn', '1985-02-10', 'lyakovich9@ifeng.com', 'Traumatología', 3779);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (36258079, 'Henderson', 'Baily', '1972-02-25', 'bhendersona@feedburner.com', 'Psicología', 7403);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (37804289, 'Pietri', 'Rodrick', '1987-09-20', 'rpietrib@buzzfeed.com', 'Psicología', 1837);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (29228930, 'Shaxby', 'Britte', '1970-12-25', 'bshaxbyc@wix.com', 'Traumatología', 6409);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (1172389, 'Fortnam', 'Wylie', '1986-10-14', 'wfortnamd@goodreads.com', 'Ginecología', 3468);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (20965475, 'Le Port', 'Allis', '1986-12-02', 'aleporte@chron.com', 'Pediatría', 6201);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (16664297, 'Treffrey', 'Gregoire', '1966-11-12', 'gtreffreyf@unesco.org', 'Psicología', 3906);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (6810396, 'Chitham', 'Ynez', '1963-04-17', 'ychithamg@1688.com', 'Dermatología', 3943);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (16564186, 'Sex', 'Virgina', '1989-10-25', 'vsexh@aol.com', 'Cardiología', 3597);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (21399451, 'Cisson', 'Eugen', '1984-12-16', 'ecissoni@wordpress.org', 'Cardiología', 5146);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (17430697, 'Berr', 'Lillian', '1965-09-08', 'lberrj@newyorker.com', 'Odontología', 6895);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (5932102, 'Lockitt', 'Nilson', '1967-05-10', 'nlockittk@360.cn', 'Oftalmología', 3703);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (34667606, 'Tillyer', 'Ulrike', '1988-09-20', 'utillyerl@dagondesign.com', 'Psicología', 2987);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (28016452, 'Seavers', 'Bay', '1970-06-02', 'bseaversm@washingtonpost.com', 'Oftalmología', 4466);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (20664636, 'Yegorovnin', 'Celestina', '1968-02-02', 'cyegorovninn@bravesites.com', 'Traumatología', 4534);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (34186737, 'Kupis', 'Myrilla', '1963-10-03', 'mkupiso@jigsy.com', 'Psicología', 2692);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (24083353, 'Josovitz', 'Randolph', '1978-04-09', 'rjosovitzp@vinaora.com', 'Cardiología', 6297);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (30330478, 'Arrington', 'Greta', '1989-06-11', 'garringtonq@drupal.org', 'Psicología', 7353);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (39052855, 'Cordes', 'Alvis', '1962-12-19', 'acordesr@blog.com', 'Psiquiatría', 7158);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (17181164, 'Gateman', 'Ingeborg', '1963-11-25', 'igatemans@homestead.com', 'Ginecología', 3969);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (26526441, 'Ciobotaru', 'Leola', '1970-06-12', 'lciobotarut@stanford.edu', 'Psiquiatría', 7542);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (34817720, 'Flinn', 'Konstanze', '1969-06-25', 'kflinnu@chron.com', 'Ginecología', 7624);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (38947935, 'Baggallay', 'Alonso', '1961-10-28', 'abaggallayv@theglobeandmail.com', 'Cardiología', 7186);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (31249716, 'Huc', 'Filippa', '1979-07-23', 'fhucw@wired.com', 'Pediatría', 3179);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (10550272, 'Robb', 'Claire', '1981-11-15', 'crobbx@bbb.org', 'Pediatría', 4613);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (37629393, 'Rennox', 'Emma', '1964-01-19', 'erennoxy@nymag.com', 'Psiquiatría', 2096);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (24937561, 'Crolla', 'Darby', '1977-10-23', 'dcrollaz@mapy.cz', 'Cardiología', 4533);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (12067631, 'Jenks', 'Carleton', '1979-12-05', 'cjenks10@cnbc.com', 'Cardiología', 2601);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (6323908, 'Lendrem', 'Claire', '1985-12-20', 'clendrem11@bloglovin.com', 'Psicología', 6122);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (28449409, 'Redbourn', 'Grier', '1973-06-10', 'gredbourn12@blogtalkradio.com', 'Clínica', 7320);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (16400925, 'Leaman', 'Florentia', '1988-01-09', 'fleaman13@webs.com', 'Oftalmología', 2839);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (3884149, 'Brigdale', 'Rosemonde', '1988-12-27', 'rbrigdale14@behance.net', 'Dermatología', 7679);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (32803094, 'Entreis', 'Lulita', '1986-06-18', 'lentreis15@lycos.com', 'Clínica', 3657);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (1461459, 'Hindmoor', 'Tyne', '1970-10-14', 'thindmoor16@elpais.com', 'Clínica', 2547);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (8524104, 'Reaney', 'Demott', '1974-09-01', 'dreaney17@dagondesign.com', 'Traumatología', 3092);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (1768279, 'Marron', 'Jessamine', '1977-04-27', 'jmarron18@jugem.jp', 'Traumatología', 2033);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (17003696, 'Hug', 'Hakeem', '1978-07-01', 'hhug19@columbia.edu', 'Clínica', 5884);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (2409919, 'Kirkland', 'Niles', '1982-11-10', 'nkirkland1a@hud.gov', 'Psiquiatría', 7090);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (26656566, 'Petren', 'Ceil', '1975-11-28', 'cpetren1b@tripadvisor.com', 'Psicología', 5951);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (16435990, 'Donovan', 'Lucho', '1982-04-18', 'ldonovan1c@microsoft.com', 'Pediatría', 7224);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (14917882, 'O''Connell', 'Mikol', '1986-08-10', 'moconnell1d@wufoo.com', 'Clínica', 7412);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (29927299, 'Musso', 'Constantine', '1988-06-30', 'cmusso1e@cmu.edu', 'Oftalmología', 4545);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (19192355, 'Grassin', 'Olivier', '1987-11-10', 'ograssin1f@studiopress.com', 'Psiquiatría', 7632);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (5754010, 'Thatcher', 'Casey', '1971-11-26', 'cthatcher1g@drupal.org', 'Odontología', 2520);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (17736934, 'Chotty', 'Symon', '1977-09-02', 'schotty1h@tripod.com', 'Ginecología', 4334);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (27519046, 'Gallifont', 'Leontyne', '1987-08-19', 'lgallifont1i@alibaba.com', 'Psiquiatría', 2085);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (30420772, 'Rushbrooke', 'Odo', '1980-03-22', 'orushbrooke1j@people.com.cn', 'Psicología', 8071);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (34805943, 'Coger', 'Westbrooke', '1978-12-20', 'wcoger1k@hc360.com', 'Ginecología', 5702);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (32905546, 'Lyptrade', 'Elke', '1977-08-18', 'elyptrade1l@unc.edu', 'Ginecología', 3149);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (27246288, 'Gudgin', 'Royce', '1969-08-28', 'rgudgin1m@arstechnica.com', 'Dermatología', 6168);
                insert into medicos (dni, apellido, nombre, fecha_nacimiento, correo_electronico, especialidad, matricula) values (7423934, 'Poker', 'Roanne', '1988-04-16', 'rpoker1n@oakley.com', 'Clínica', 6874);
-- PARA CHEQUEAR QUE LOS DATOS SE CARGARON CORRECTAMENTE, PUEDE DESCOMENTAR Y EJECUTAR LA SIGUIENTE LINEA  
-- SELECT * FROM medicos;


-- Inserción de datos en la tabla 'telefono_medico' con los 'id' consultados
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (1, 'CELULAR', '7135103403');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (2, 'FIJO', '8177229776');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (3, 'CELULAR', '8111466994');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (4, 'FIJO', '4317675511');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (5, 'FIJO', '3826661990');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (6, 'FIJO', '3331940463');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (7, 'FIJO', '2404051654');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (8, 'CELULAR', '4475285935');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (9, 'FIJO', '6328350976');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (10, 'CELULAR', '9329478840');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (11, 'CELULAR', '7307585835');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (12, 'CELULAR', '5183008945');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (13, 'FIJO', '9993835687');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (14, 'CELULAR', '1258859771');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (15, 'CELULAR', '6862115601');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (16, 'CELULAR', '9979857588');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (17, 'FIJO', '1942753354');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (18, 'CELULAR', '7061917675');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (19, 'FIJO', '1379517288');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (20, 'CELULAR', '2992961401');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (21, 'FIJO', '3136545640');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (22, 'FIJO', '5544156156');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (23, 'FIJO', '2678836742');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (24, 'CELULAR', '4102408024');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (25, 'CELULAR', '4984817031');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (26, 'FIJO', '6842369287');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (27, 'CELULAR', '9314237277');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (28, 'CELULAR', '5126980020');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (29, 'CELULAR', '5894449365');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (30, 'FIJO', '8551230703');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (31, 'FIJO', '3936927781');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (32, 'CELULAR', '6365964612');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (33, 'FIJO', '4955611024');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (34, 'CELULAR', '8808749410');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (35, 'CELULAR', '8239956609');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (36, 'FIJO', '9957385671');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (37, 'CELULAR', '4196195623');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (38, 'FIJO', '6631489085');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (39, 'FIJO', '6005817090');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (40, 'CELULAR', '7982640409');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (41, 'CELULAR', '1243203539');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (42, 'FIJO', '4345172246');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (43, 'FIJO', '3279629094');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (44, 'FIJO', '8109419550');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (45, 'FIJO', '3847773978');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (46, 'FIJO', '8175700236');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (47, 'CELULAR', '9499760222');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (48, 'FIJO', '5346000709');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (49, 'FIJO', '3132354063');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (50, 'FIJO', '6342787476');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (51, 'FIJO', '3807058712');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (52, 'CELULAR', '1613709370');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (53, 'CELULAR', '7228028357');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (54, 'FIJO', '8295640089');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (55, 'FIJO', '8595852668');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (56, 'FIJO', '7858303245');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (57, 'CELULAR', '1431070102');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (58, 'CELULAR', '4235061126');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (59, 'FIJO', '8536964913');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (60, 'FIJO', '6257868393');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (1, 'CELULAR', '3205201158');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (32, 'CELULAR', '2143088343');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (3, 'CELULAR', '5229362894');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (45, 'FIJO', '6657546629');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (5, 'CELULAR', '1328381403');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (60, 'CELULAR', '5561819373');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (7, 'FIJO', '8278366262');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (18, 'CELULAR', '1132633850');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (9, 'FIJO', '6085872577');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (10, 'FIJO', '6998362634');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (51, 'CELULAR', '5159611703');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (22, 'FIJO', '1878707655');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (3, 'FIJO', '7808712690');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (24, 'CELULAR', '6323467812');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (25, 'CELULAR', '3805526109');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (26, 'CELULAR', '1975366970');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (47, 'FIJO', '5734667060');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (48, 'CELULAR', '9896857658');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (49, 'CELULAR', '8642340066');
              insert into medicos_telefonos (id_medico, descripcion, telefono) values (12, 'CELULAR', '2067034457');
-- PARA CHEQUEAR QUE LOS DATOS SE CARGARON CORRECTAMENTE, PUEDE DESCOMENTAR Y EJECUTAR LA SIGUIENTE LINEA  
-- SELECT * FROM medicos_telefonos;