--  ESTE SCRIPT CARGA DATOS A LA TABLA 'historiales_medicos'
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (159, 59, '2023-03-24', 'Alergia estacional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (135, 13, '2023-07-05', 'Otitis externa');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (166, 41, '2023-04-06', 'Lumbalgia');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (54, 46, '2023-03-15', 'Esguince de tobillo');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (39, 35, '2023-02-15', 'Bronquitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (67, 15, '2023-07-22', 'Lumbalgia');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (165, 49, '2023-07-18', 'Hipertensión');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (66, 47, '2023-07-18', 'Bronquitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (123, 48, '2023-07-16', 'Dermatitis leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (170, 40, '2023-05-19', 'Lumbalgia');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (66, 60, '2023-02-28', 'Tendinitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (15, 18, '2023-02-18', 'Contractura muscular');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (33, 11, '2023-06-26', 'Sinusitis aguda');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (77, 52, '2023-07-16', 'Contractura muscular');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (113, 12, '2023-05-02', 'Bronquitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (13, 16, '2023-03-10', 'Cálculos renales');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (78, 23, '2023-03-24', 'Lumbalgia');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (123, 10, '2023-03-31', 'Urticaria');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (114, 48, '2023-07-13', 'Hipertensión');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (29, 16, '2023-01-30', 'Sinusitis aguda');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (46, 30, '2023-01-19', 'Diabetes tipo 2');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (163, 43, '2023-03-20', 'Reflujo gastroesofágico');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (52, 26, '2023-04-15', 'Lumbalgia');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (1, 17, '2023-03-15', 'Conjuntivitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (111, 38, '2023-05-08', 'Contractura muscular');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (24, 16, '2023-05-22', 'Infección de garganta');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (161, 8, '2023-05-15', 'Gripe común');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (40, 30, '2023-07-15', 'Alergia estacional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (112, 46, '2023-02-10', 'Fatiga crónica');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (102, 45, '2023-01-29', 'Insomnio ocasional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (93, 38, '2023-08-05', 'Infección de garganta');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (40, 37, '2023-03-13', 'Fatiga crónica');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (48, 47, '2023-03-27', 'Depresión leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (146, 36, '2023-03-05', 'Urticaria');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (78, 42, '2023-05-13', 'Cálculos renales');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (165, 54, '2023-04-22', 'Otitis externa');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (25, 12, '2023-06-28', 'Neumonía leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (42, 28, '2023-02-18', 'Síndrome del túnel carpiano');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (61, 4, '2023-07-25', 'Migraña');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (81, 48, '2023-05-27', 'Alergia estacional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (6, 26, '2023-05-15', 'Bronquitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (152, 25, '2023-02-19', 'Reflujo gastroesofágico');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (68, 9, '2023-01-25', 'Dermatitis leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (90, 8, '2023-06-24', 'Escoliosis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (100, 21, '2023-02-02', 'Contractura muscular');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (137, 30, '2023-06-26', 'Bronquitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (98, 60, '2023-07-07', 'Rinitis alérgica');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (165, 41, '2023-02-21', 'Gastritis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (7, 59, '2023-05-15', 'Migraña');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (160, 9, '2023-07-04', 'Rinitis alérgica');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (7, 43, '2023-02-20', 'Síndrome del túnel carpiano');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (68, 22, '2023-05-19', 'Tendinitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (56, 48, '2023-07-23', 'Sinusitis aguda');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (115, 19, '2023-02-17', 'Lumbalgia');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (169, 9, '2023-06-06', 'Neumonía leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (10, 1, '2023-05-06', 'Reflujo gastroesofágico');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (127, 60, '2023-04-04', 'Gripe común');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (45, 40, '2023-03-08', 'Dermatitis leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (31, 11, '2023-06-29', 'Urticaria');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (13, 21, '2023-02-14', 'Hernia discal lumbar');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (106, 15, '2023-03-19', 'Tendinitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (19, 39, '2023-02-07', 'Infección de garganta');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (81, 51, '2023-02-19', 'Insomnio ocasional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (60, 54, '2023-06-30', 'Otitis externa');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (87, 56, '2023-02-07', 'Síndrome del túnel carpiano');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (5, 30, '2023-06-21', 'Fatiga crónica');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (170, 43, '2023-06-26', 'Cálculos renales');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (93, 15, '2023-02-02', 'Gastritis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (160, 13, '2023-02-03', 'Neumonía leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (47, 35, '2023-04-13', 'Infección de garganta');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (19, 23, '2023-01-09', 'Anemia leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (112, 7, '2023-06-21', 'Alergia estacional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (122, 49, '2023-02-14', 'Fatiga crónica');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (38, 53, '2023-04-14', 'Migraña');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (76, 13, '2023-03-04', 'Otitis externa');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (142, 7, '2023-01-22', 'Cálculos renales');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (128, 60, '2023-02-15', 'Migraña');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (105, 32, '2023-04-30', 'Urticaria');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (30, 30, '2023-06-16', 'Síndrome del túnel carpiano');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (140, 2, '2023-07-11', 'Diabetes tipo 2');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (106, 50, '2023-05-11', 'Reflujo gastroesofágico');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (28, 21, '2023-03-20', 'Escoliosis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (155, 32, '2023-03-27', 'Migraña');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (68, 58, '2023-03-27', 'Bronquitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (87, 27, '2023-04-19', 'Diabetes tipo 2');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (30, 48, '2023-03-19', 'Conjuntivitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (12, 9, '2023-02-08', 'Diabetes tipo 2');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (78, 48, '2023-01-31', 'Tendinitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (125, 3, '2023-02-18', 'Dermatitis leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (41, 43, '2023-05-07', 'Esguince de tobillo');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (138, 20, '2023-06-08', 'Insomnio ocasional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (7, 38, '2023-03-18', 'Hipertensión');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (39, 44, '2023-05-02', 'Tendinitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (140, 9, '2023-04-25', 'Anemia leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (66, 18, '2023-02-03', 'Neumonía leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (102, 17, '2023-06-14', 'Depresión leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (6, 11, '2023-04-27', 'Gastritis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (74, 13, '2023-08-12', 'Neumonía leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (6, 10, '2023-05-08', 'Hernia discal lumbar');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (84, 18, '2023-01-27', 'Neumonía leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (88, 51, '2023-06-24', 'Reflujo gastroesofágico');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (119, 53, '2023-06-20', 'Síndrome del túnel carpiano');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (144, 2, '2023-03-16', 'Depresión leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (83, 8, '2023-01-30', 'Diabetes tipo 2');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (15, 51, '2023-02-10', 'Síndrome del túnel carpiano');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (11, 53, '2023-03-01', 'Neumonía leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (14, 29, '2023-03-12', 'Alergia estacional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (68, 9, '2023-02-16', 'Sinusitis aguda');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (25, 60, '2023-07-27', 'Varicela');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (89, 18, '2023-07-13', 'Otitis externa');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (57, 40, '2023-01-30', 'Urticaria');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (32, 56, '2023-07-12', 'Cistitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (18, 31, '2023-02-22', 'Dermatitis leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (170, 29, '2023-06-26', 'Reflujo gastroesofágico');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (126, 38, '2023-05-08', 'Diabetes tipo 2');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (60, 52, '2023-02-18', 'Conjuntivitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (148, 15, '2023-05-13', 'Fatiga crónica');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (25, 55, '2023-06-15', 'Infección de garganta');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (75, 28, '2023-06-13', 'Contractura muscular');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (77, 38, '2023-04-15', 'Diabetes tipo 2');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (85, 46, '2023-03-24', 'Gripe común');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (19, 41, '2023-07-21', 'Varicela');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (55, 37, '2023-07-17', 'Depresión leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (138, 15, '2023-07-09', 'Insomnio ocasional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (36, 45, '2023-07-22', 'Insomnio ocasional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (124, 12, '2023-07-05', 'Tendinitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (127, 20, '2023-06-30', 'Lumbalgia');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (147, 25, '2023-04-08', 'Escoliosis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (128, 6, '2023-05-23', 'Urticaria');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (115, 41, '2023-06-27', 'Cistitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (115, 4, '2023-06-16', 'Gastritis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (55, 15, '2023-01-15', 'Sinusitis aguda');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (136, 12, '2023-06-14', 'Tendinitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (53, 49, '2023-08-10', 'Gripe común');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (23, 45, '2023-06-23', 'Anemia leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (84, 25, '2023-01-29', 'Sinusitis aguda');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (123, 38, '2023-07-24', 'Lumbalgia');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (77, 57, '2023-02-11', 'Síndrome del túnel carpiano');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (29, 7, '2023-06-27', 'Alergia estacional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (20, 17, '2023-08-08', 'Gastritis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (146, 4, '2023-06-06', 'Rinitis alérgica');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (7, 52, '2023-07-27', 'Escoliosis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (100, 43, '2023-05-25', 'Contractura muscular');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (89, 6, '2023-08-11', 'Sinusitis aguda');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (161, 35, '2023-03-08', 'Cálculos renales');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (143, 34, '2023-04-19', 'Depresión leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (53, 13, '2023-07-06', 'Neumonía leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (89, 9, '2023-07-10', 'Alergia estacional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (49, 45, '2023-03-31', 'Otitis externa');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (169, 14, '2023-02-21', 'Conjuntivitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (121, 1, '2023-01-23', 'Insomnio ocasional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (118, 59, '2023-03-23', 'Esguince de tobillo');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (103, 43, '2023-08-08', 'Esguince de tobillo');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (1, 45, '2023-02-03', 'Insomnio ocasional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (61, 26, '2023-08-03', 'Conjuntivitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (44, 54, '2023-03-19', 'Anemia leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (36, 32, '2023-01-09', 'Dermatitis leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (52, 10, '2023-06-16', 'Anemia leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (162, 58, '2023-01-16', 'Sinusitis aguda');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (125, 27, '2023-04-01', 'Síndrome del túnel carpiano');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (26, 34, '2023-02-01', 'Reflujo gastroesofágico');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (72, 45, '2023-07-21', 'Neumonía leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (1, 56, '2023-02-28', 'Lumbalgia');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (42, 8, '2023-01-25', 'Cálculos renales');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (164, 40, '2023-02-06', 'Cálculos renales');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (55, 55, '2023-02-14', 'Varicela');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (8, 50, '2023-08-14', 'Conjuntivitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (39, 38, '2023-04-28', 'Migraña');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (29, 57, '2023-05-02', 'Esguince de tobillo');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (38, 5, '2023-04-09', 'Neumonía leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (90, 51, '2023-01-08', 'Tendinitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (167, 15, '2023-04-23', 'Cálculos renales');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (19, 58, '2023-05-06', 'Otitis externa');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (130, 45, '2023-05-13', 'Bronquitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (119, 55, '2023-05-20', 'Migraña');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (107, 38, '2023-06-24', 'Otitis externa');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (159, 40, '2023-06-15', 'Esguince de tobillo');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (103, 51, '2023-07-11', 'Bronquitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (30, 27, '2023-05-03', 'Migraña');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (76, 48, '2023-01-12', 'Otitis externa');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (108, 24, '2023-02-17', 'Varicela');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (93, 59, '2023-04-13', 'Reflujo gastroesofágico');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (92, 36, '2023-06-14', 'Reflujo gastroesofágico');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (41, 20, '2023-07-31', 'Cistitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (41, 12, '2023-03-08', 'Dermatitis leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (155, 31, '2023-07-06', 'Gastritis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (50, 44, '2023-05-09', 'Hipertensión');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (2, 53, '2023-07-17', 'Varicela');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (44, 58, '2023-06-30', 'Urticaria');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (161, 2, '2023-06-07', 'Alergia estacional');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (90, 13, '2023-05-08', 'Tendinitis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (145, 9, '2023-04-28', 'Varicela');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (146, 47, '2023-04-07', 'Otitis externa');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (99, 28, '2023-02-17', 'Lumbalgia');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (88, 7, '2023-05-21', 'Lumbalgia');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (151, 31, '2023-08-01', 'Rinitis alérgica');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (20, 9, '2023-05-31', 'Varicela');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (33, 53, '2023-01-23', 'Neumonía leve');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (91, 19, '2023-06-29', 'Escoliosis');
                insert into historiales_medicos (id_paciente, id_medico, fecha_registro, nota_medica) values (122, 18, '2023-05-18', 'Gripe común');
-- PARA CHEQUEAR QUE LOS DATOS HAYAN SIDO CARGADOS CORRECTAMENTE, DESCOMENTAR Y EJECUTAR LA SIGUIENTE LÍNEA
-- SELECT * FROM historiales_medicos;