-- ESTE SCRIPT INSERTA DATOS EN LA TABLA 'recetas'
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (18, 64, 27, 'Colonoscopia virtual', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 6, 2, 'Aspirina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 161, 38, 'Ecocardiograma', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 97, 16, 'Losartán', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 11, 54, 'Fluoxetina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 153, 13, 'Resonancia magnética (RM)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 90, 7, 'Tomografía de cráneo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 51, 35, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 105, 27, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 63, 41, 'Prueba de glucosa en ayunas', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 165, 57, 'Ecocardiograma', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 17, 15, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (9, 82, 13, 'Ecografía abdominal', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 55, 32, 'Omeprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 128, 38, 'Prueba de tolerancia a la glucosa', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 108, 40, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 150, 55, 'Insulina glargina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 15, 2, 'Metoclopramida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 103, 57, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 146, 39, 'Tomografía computarizada (TC)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 116, 56, 'Prueba de esfuerzo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 23, 39, 'Análisis de sangre completo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (11, 43, 26, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 127, 50, 'Holter de ritmo cardíaco', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 71, 57, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 134, 54, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (9, 94, 26, 'Hidroclorotiazida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (11, 54, 38, 'Loratadina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 15, 58, 'Fluoxetina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 23, 18, 'Insulina glargina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (27, 145, 24, 'Metformina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 51, 49, 'Metformina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 132, 49, 'Dipirona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 151, 10, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 13, 12, 'Colonoscopia', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (9, 13, 26, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (25, 117, 53, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 23, 31, 'Tomografía de cráneo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (19, 24, 6, 'Prueba de glucosa en ayunas', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 165, 19, 'Alprazolam', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (17, 93, 42, 'Endoscopia digestiva', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 130, 21, 'Electrocardiograma (ECG)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 64, 17, 'Prednisona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 152, 54, 'Ecografía abdominal', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 101, 42, 'Metoclopramida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (19, 57, 52, 'Warfarina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 65, 6, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 24, 58, 'Insulina glargina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (12, 166, 2, 'Atorvastatina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 43, 40, 'Atorvastatina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (17, 149, 14, 'Escitalopram', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 156, 33, 'Holter de ritmo cardíaco', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 91, 28, 'Endoscopia digestiva', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 99, 51, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 83, 10, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 122, 60, 'Paracetamol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 116, 41, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 149, 38, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (25, 166, 43, 'Aspirina', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 108, 21, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 13, 29, 'Biopsia de piel', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (19, 46, 19, 'Dipirona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (27, 18, 22, 'Fundoscopía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 84, 40, 'Ibuprofeno', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 32, 32, 'Dipirona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 24, 48, 'Fluoxetina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 35, 39, 'Prednisona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 42, 35, 'Amoxicilina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 153, 17, 'Omeprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 120, 20, 'Loratadina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (11, 36, 40, 'Amoxicilina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (32, 110, 53, 'Análisis de sangre completo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 148, 22, 'Pantoprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 92, 4, 'Insulina glargina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 143, 31, 'Omeprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (11, 81, 55, 'Alprazolam', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 162, 52, 'Salbutamol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 21, 3, 'Esofagogastroduodenoscopia (EGD)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 63, 7, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 30, 39, 'Cetirizina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 125, 19, 'Hidroclorotiazida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 96, 35, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (9, 7, 30, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 43, 23, 'Metoclopramida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 13, 49, 'Fundoscopía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 130, 27, 'Insulina glargina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 34, 46, 'Prednisona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 148, 48, 'Prueba de Papanicolaou', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 164, 48, 'Metformina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 1, 59, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 77, 59, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 79, 27, 'Montelukast', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 29, 33, 'Metformina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 77, 6, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 44, 10, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 110, 50, 'Amoxicilina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 87, 43, 'Naproxeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 145, 37, 'Loratadina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 49, 37, 'Omeprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (28, 165, 28, 'Metformina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 119, 4, 'Endoscopia digestiva', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 45, 6, 'Alprazolam', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (27, 110, 49, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 10, 37, 'Naproxeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 107, 56, 'Tomografía de cráneo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 54, 28, 'Amlodipino', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 110, 15, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 89, 55, 'Salbutamol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (18, 120, 43, 'Holter de ritmo cardíaco', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 11, 3, 'Escitalopram', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (35, 155, 52, 'Enalapril', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (18, 141, 47, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (18, 81, 33, 'Prednisona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (12, 36, 18, 'Densitometría ósea', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 21, 30, 'Naproxeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (9, 130, 57, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 71, 42, 'Electrocardiograma (ECG)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 138, 5, 'Ecocardiograma', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 124, 4, 'Amoxicilina', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 113, 56, 'Levotiroxina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 48, 24, 'Dipirona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 88, 8, 'Omeprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 141, 37, 'Examen de orina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (28, 118, 4, 'Prueba de Papanicolaou', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (12, 97, 46, 'Mamografía', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (18, 51, 53, 'Prueba de tolerancia a la glucosa', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 38, 55, 'Fluoxetina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 71, 12, 'Levotiroxina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 129, 17, 'Cetirizina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 121, 17, 'Prednisona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 109, 7, 'Fundoscopía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 20, 55, 'Losartán', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 17, 46, 'Fundoscopía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 1, 15, 'Tomografía computarizada (TC)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 111, 47, 'Electrocardiograma (ECG)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 79, 52, 'Escitalopram', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (9, 149, 57, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 151, 24, 'Biopsia de piel', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 77, 46, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 43, 19, 'Fluoxetina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 123, 19, 'Hemocultivo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 66, 37, 'Amoxicilina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 121, 17, 'Prueba de tolerancia a la glucosa', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (18, 54, 46, 'Losartán', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 135, 17, 'Metoclopramida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 41, 2, 'Examen de orina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 5, 56, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 136, 9, 'Atorvastatina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 152, 26, 'Endoscopia digestiva', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 122, 27, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 91, 55, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 67, 17, 'Warfarina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 69, 11, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 76, 29, 'Losartán', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 153, 25, 'Paracetamol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 42, 16, 'Salbutamol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 56, 6, 'Examen de orina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 106, 11, 'Alprazolam', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 68, 27, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 7, 39, 'Cetirizina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (27, 140, 25, 'Examen de orina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 142, 3, 'Prueba de esfuerzo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 142, 38, 'Levotiroxina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 11, 33, 'Holter de ritmo cardíaco', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (35, 73, 12, 'Codeína', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 159, 1, 'Fundoscopía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (12, 116, 19, 'Resonancia magnética (RM)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (35, 127, 28, 'Codeína', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 157, 32, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 31, 9, 'Holter de ritmo cardíaco', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 84, 2, 'Prueba de embarazo en sangre', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 111, 49, 'Enalapril', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 78, 9, 'Cetirizina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 131, 37, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 38, 33, 'Examen de orina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 1, 8, 'Codeína', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 66, 19, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 103, 27, 'Ciprofloxacina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 63, 53, 'Electrocardiograma (ECG)', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (27, 126, 54, 'Biopsia de piel', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 110, 22, 'Esofagogastroduodenoscopia (EGD)', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 83, 4, 'Prueba de esfuerzo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 10, 14, 'Aspirina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 107, 52, 'Densitometría ósea', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (11, 34, 7, 'Metoclopramida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 92, 3, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 86, 32, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (35, 161, 5, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 140, 28, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 170, 6, 'Radiografía de tórax', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 65, 58, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (11, 153, 13, 'Pantoprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 164, 47, 'Insulina glargina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 167, 9, 'Esofagogastroduodenoscopia (EGD)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (17, 58, 18, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 33, 6, 'Fluoxetina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (18, 104, 34, 'Endoscopia digestiva', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 33, 53, 'Prueba de embarazo en sangre', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (9, 21, 18, 'Resonancia magnética (RM)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (27, 112, 14, 'Loratadina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (17, 23, 27, 'Naproxeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 142, 33, 'Ecocardiograma', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 138, 29, 'Loratadina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 83, 34, 'Biopsia de piel', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 60, 31, 'Fundoscopía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (12, 12, 1, 'Biopsia de piel', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 7, 41, 'Prueba de Papanicolaou', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 4, 12, 'Resonancia magnética (RM)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 100, 55, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (11, 62, 29, 'Endoscopia digestiva', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 125, 17, 'Fluoxetina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 83, 14, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 37, 56, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 158, 56, 'Cetirizina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (25, 42, 35, 'Examen de orina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (17, 63, 58, 'Tomografía de cráneo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (32, 13, 53, 'Tomografía de cráneo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 51, 22, 'Pantoprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (27, 154, 9, 'Ranitidina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 110, 6, 'Dipirona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 14, 37, 'Hidroclorotiazida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 9, 14, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 58, 44, 'Losartán', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (9, 129, 50, 'Omeprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (27, 168, 10, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 120, 14, 'Warfarina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 58, 37, 'Biopsia de piel', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 84, 52, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 7, 32, 'Tomografía de cráneo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 91, 7, 'Fluoxetina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 10, 29, 'Tomografía de cráneo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 30, 53, 'Pantoprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 133, 43, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 166, 13, 'Ecografía abdominal', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (18, 29, 9, 'Examen de orina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 143, 30, 'Ecocardiograma', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (35, 41, 50, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 167, 44, 'Omeprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 113, 18, 'Amlodipino', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 18, 52, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 51, 3, 'Tomografía computarizada (TC)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 82, 30, 'Loratadina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 127, 1, 'Salbutamol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 145, 37, 'Ciprofloxacina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 84, 1, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 119, 56, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (32, 58, 51, 'Fluoxetina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 88, 51, 'Loratadina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 89, 26, 'Pantoprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (32, 59, 49, 'Análisis de sangre completo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 95, 29, 'Atorvastatina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 22, 41, 'Atorvastatina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 33, 42, 'Dipirona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 81, 19, 'Enalapril', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 111, 24, 'Loratadina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 61, 15, 'Hemocultivo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 168, 60, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 40, 36, 'Radiografía de tórax', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 112, 56, 'Naproxeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (11, 121, 4, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 84, 22, 'Codeína', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 74, 50, 'Cetirizina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 138, 60, 'Tomografía computarizada (TC)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (12, 169, 48, 'Atorvastatina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 131, 51, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (25, 74, 21, 'Salbutamol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 48, 17, 'Metoclopramida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (17, 2, 36, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (19, 66, 33, 'Omeprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 74, 45, 'Prueba de embarazo en sangre', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 112, 37, 'Biopsia de piel', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 21, 53, 'Prueba de embarazo en sangre', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 84, 59, 'Mamografía', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 136, 4, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 33, 36, 'Levotiroxina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 69, 16, 'Prueba de Papanicolaou', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (28, 46, 55, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 103, 59, 'Codeína', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 58, 27, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (35, 24, 50, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 93, 40, 'Levotiroxina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 11, 39, 'Codeína', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (18, 158, 10, 'Fluoxetina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 5, 25, 'Levotiroxina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (12, 98, 39, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (32, 19, 28, 'Prueba de Papanicolaou', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 150, 12, 'Warfarina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (19, 124, 42, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 165, 55, 'Hidroclorotiazida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 162, 60, 'Hidroclorotiazida', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 134, 59, 'Omeprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 7, 8, 'Prueba de función pulmonar', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 83, 8, 'Prednisona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 87, 45, 'Enalapril', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 143, 8, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 136, 36, 'Prednisona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 38, 22, 'Examen de orina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 155, 50, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (9, 45, 17, 'Levotiroxina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 159, 23, 'Aspirina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 106, 54, 'Escitalopram', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 29, 32, 'Holter de ritmo cardíaco', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 105, 18, 'Amlodipino', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 55, 21, 'Metformina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 70, 23, 'Ranitidina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 165, 8, 'Atorvastatina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 141, 35, 'Densitometría ósea', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 125, 10, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 122, 18, 'Alprazolam', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 78, 26, 'Audiometría', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 20, 1, 'Alprazolam', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 100, 53, 'Ciprofloxacina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (11, 113, 17, 'Alprazolam', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 68, 9, 'Hidroclorotiazida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 88, 53, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 131, 4, 'Losartán', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 157, 12, 'Atorvastatina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 48, 21, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (11, 112, 53, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 144, 42, 'Prueba de función pulmonar', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (32, 65, 54, 'Metoclopramida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 65, 45, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (32, 153, 8, 'Ciprofloxacina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (19, 102, 2, 'Amlodipino', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 150, 36, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 75, 21, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 52, 27, 'Colonoscopia virtual', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (25, 41, 34, 'Ciprofloxacina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 101, 11, 'Tomografía computarizada (TC)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 52, 32, 'Densitometría ósea', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 127, 32, 'Prednisona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 119, 23, 'Montelukast', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 152, 23, 'Examen de orina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 105, 15, 'Escitalopram', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 22, 44, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 90, 15, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 82, 39, 'Salbutamol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (19, 119, 45, 'Prueba de glucosa en ayunas', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 28, 60, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 131, 29, 'Tomografía computarizada (TC)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (27, 12, 24, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 164, 27, 'Metformina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 135, 7, 'Tomografía de cráneo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 82, 5, 'Loratadina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 23, 57, 'Pantoprazol', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (12, 101, 44, 'Fundoscopía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 137, 19, 'Levotiroxina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 14, 2, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (19, 119, 41, 'Cetirizina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 147, 1, 'Esofagogastroduodenoscopia (EGD)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 30, 10, 'Metformina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 102, 23, 'Metoclopramida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (17, 111, 21, 'Fundoscopía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (9, 70, 11, 'Biopsia de piel', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 60, 8, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 6, 53, 'Biopsia de piel', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 44, 17, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 151, 6, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 49, 28, 'Warfarina', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 110, 4, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 82, 40, 'Furosemida', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 150, 14, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 99, 41, 'Prueba de glucosa en ayunas', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 39, 21, 'Amlodipino', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 63, 26, 'Prueba de tolerancia a la glucosa', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (8, 10, 45, 'Prueba de embarazo en sangre', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 71, 53, 'Insulina glargina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 115, 60, 'Ecocardiograma', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 75, 58, 'Electrocardiograma (ECG)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (27, 45, 17, 'Metformina', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 155, 28, 'Naproxeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 137, 17, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 13, 13, 'Amoxicilina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (12, 56, 57, 'Amlodipino', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (28, 82, 3, 'Alprazolam', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (19, 49, 50, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 165, 55, 'Montelukast', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 153, 14, 'Tomografía computarizada (TC)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 133, 12, 'Examen de orina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 29, 19, 'Análisis de sangre completo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (12, 23, 60, 'Resonancia magnética (RM)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 43, 53, 'Prueba de embarazo en sangre', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 30, 32, 'Cetirizina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 162, 26, 'Colonoscopia', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 14, 45, 'Hemocultivo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 50, 30, 'Alprazolam', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 144, 6, 'Esofagogastroduodenoscopia (EGD)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 84, 19, 'Alprazolam', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 95, 7, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 151, 58, 'Prueba de tolerancia a la glucosa', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 110, 35, 'Resonancia magnética (RM)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 40, 48, 'Fundoscopía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 77, 1, 'Examen de orina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 50, 6, 'Furosemida', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 15, 37, 'Tomografía computarizada (TC)', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (13, 78, 1, 'Ciprofloxacina', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (28, 136, 15, 'Ecografía abdominal', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 140, 46, 'Losartán', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 101, 38, 'Naproxeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 102, 46, 'Audiometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 125, 58, 'Warfarina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 20, 42, 'Colonoscopia virtual', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 106, 49, 'Alprazolam', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 128, 52, 'Aspirina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 44, 12, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 18, 58, 'Insulina glargina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (11, 93, 28, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 131, 46, 'Warfarina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 52, 46, 'Fundoscopía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 86, 33, 'Prueba de esfuerzo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 124, 1, 'Amlodipino', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (2, 37, 13, 'Prueba de embarazo en sangre', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 51, 29, 'Endoscopia digestiva', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 62, 35, 'Hemocultivo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 95, 53, 'Paracetamol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 72, 18, 'Tomografía de cráneo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (32, 9, 3, 'Biopsia de piel', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 57, 5, 'Colonoscopia virtual', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 5, 26, 'Losartán', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 118, 5, 'Prednisona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 44, 14, 'Resonancia magnética (RM)', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 11, 51, 'Prueba de glucosa en ayunas', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (18, 156, 27, 'Ecocardiograma', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 9, 32, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 161, 7, 'Análisis de sangre completo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 7, 13, 'Warfarina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 44, 34, 'Electrocardiograma (ECG)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 165, 40, 'Ranitidina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 108, 16, 'Prueba de esfuerzo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (20, 28, 51, 'Biopsia de piel', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 126, 59, 'Paracetamol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (28, 72, 1, 'Esofagogastroduodenoscopia (EGD)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (29, 164, 19, 'Ecografía abdominal', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 46, 11, 'Ecocardiograma', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (32, 151, 31, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (35, 61, 28, 'Amoxicilina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 166, 53, 'Fundoscopía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (25, 33, 42, 'Endoscopia digestiva', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (34, 79, 1, 'Paracetamol', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 116, 11, 'Alprazolam', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (35, 98, 25, 'Densitometría ósea', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 76, 30, 'Dipirona', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 81, 9, 'Omeprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (30, 122, 46, 'Cetirizina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (1, 69, 7, 'Amoxicilina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 8, 52, 'Ranitidina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (17, 120, 10, 'Radiografía de tórax', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (26, 82, 41, 'Metformina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (10, 70, 12, 'Pantoprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 123, 38, 'Enalapril', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 83, 48, 'Endoscopia digestiva', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 13, 59, 'Amoxicilina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 52, 7, 'Atorvastatina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 2, 49, 'Cetirizina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (7, 17, 30, 'Ecografía abdominal', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (21, 112, 3, 'Levotiroxina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 104, 8, 'Warfarina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (6, 46, 17, 'Montelukast', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (24, 3, 50, 'Resonancia magnética (RM)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 99, 38, 'Naproxeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (35, 83, 37, 'Prueba de glucosa en ayunas', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (4, 124, 29, 'Radiografía de tórax', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (17, 35, 52, 'Losartán', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (19, 14, 21, 'Hemocultivo', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 124, 46, 'Paracetamol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (28, 150, 46, 'Ranitidina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 73, 49, 'Ecografía abdominal', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 99, 49, 'Radiografía de tórax', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (16, 147, 30, 'Tomografía computarizada (TC)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 70, 42, 'Montelukast', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (17, 113, 19, 'Ibuprofeno', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (23, 45, 44, 'Examen de orina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 99, 28, 'Levotiroxina', 'NORMAL');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 4, 4, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 145, 28, 'Prueba de glucosa en ayunas', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 46, 34, 'Ecocardiograma', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 115, 31, 'Densitometría ósea', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 31, 49, 'Levotiroxina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (18, 55, 24, 'Metformina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (31, 63, 4, 'Prednisona', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (33, 104, 15, 'Codeína', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 124, 44, 'Loratadina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (35, 146, 50, 'Mamografía', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (17, 108, 5, 'Ecografía abdominal', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 68, 23, 'Resonancia magnética (RM)', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (22, 106, 36, 'Ergometría', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (5, 158, 12, 'Amlodipino', 'URGENTE');
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (14, 72, 58, 'Examen de orina', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (15, 139, 33, 'Pantoprazol', null);
                insert into recetas (id_obra_social, id_paciente, id_medico, medicamento_recetado, notas_adicionales) values (3, 98, 52, 'Dipirona', null);
-- PARA CHEQUEAR QUE LOS DATOS HAYAN SIDO CARGADOS CORRECTAMENTE, DESCOMENTAR Y EJECUTAR LA SIGUIENTE LÍNEA
-- SELECT * FROM recetas;


-- SE EJECUTAN LOS SIGUIENTES STORED PROCEDURES, PARA ACTUALIZAR EL CONTENIDO DE LAS TABLAS CORRESPONDIENTES
CALL sp_ingresos_facturacion_mensual();
CALL sp_rendimiento_medico();

